name: Deploy to Minikube 

on: push
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master  
    - name: Deploy to minikube
      run:
        kubectl apply -f k8s-node-deploy.yaml
    - name: Sleep for 15 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
    - name: Try the cluster !
      run: kubectl get pods -A   
    - name: Test service URLs
      run: |
          minikube service list
          minikube service nodejs-app --url
          curl $(minikube service nodejs-app --url)        
